// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

/*
Package models is a generated protocol buffer package.

It is generated from these files:
	service.proto

It has these top-level messages:
	AuthRequest
	AuthResponse
	GetUserRequest
	GetUserResponse
*/
package models

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "google.golang.org/genproto/googleapis/api/annotations"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type AuthRequest struct {
	Email    string `protobuf:"bytes,1,opt,name=email" json:"email,omitempty"`
	Password string `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
}

func (m *AuthRequest) Reset()                    { *m = AuthRequest{} }
func (m *AuthRequest) String() string            { return proto.CompactTextString(m) }
func (*AuthRequest) ProtoMessage()               {}
func (*AuthRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *AuthRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *AuthRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

type AuthResponse struct {
	Done bool `protobuf:"varint,1,opt,name=done" json:"done,omitempty"`
}

func (m *AuthResponse) Reset()                    { *m = AuthResponse{} }
func (m *AuthResponse) String() string            { return proto.CompactTextString(m) }
func (*AuthResponse) ProtoMessage()               {}
func (*AuthResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthResponse) GetDone() bool {
	if m != nil {
		return m.Done
	}
	return false
}

type GetUserRequest struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *GetUserRequest) Reset()                    { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string            { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()               {}
func (*GetUserRequest) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *GetUserRequest) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

type GetUserResponse struct {
	Id   string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,3,opt,name=age" json:"age,omitempty"`
}

func (m *GetUserResponse) Reset()                    { *m = GetUserResponse{} }
func (m *GetUserResponse) String() string            { return proto.CompactTextString(m) }
func (*GetUserResponse) ProtoMessage()               {}
func (*GetUserResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetUserResponse) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GetUserResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *GetUserResponse) GetAge() int32 {
	if m != nil {
		return m.Age
	}
	return 0
}

func init() {
	proto.RegisterType((*AuthRequest)(nil), "models.AuthRequest")
	proto.RegisterType((*AuthResponse)(nil), "models.AuthResponse")
	proto.RegisterType((*GetUserRequest)(nil), "models.GetUserRequest")
	proto.RegisterType((*GetUserResponse)(nil), "models.GetUserResponse")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for AuthService service

type AuthServiceClient interface {
	Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error)
}

type authServiceClient struct {
	cc *grpc.ClientConn
}

func NewAuthServiceClient(cc *grpc.ClientConn) AuthServiceClient {
	return &authServiceClient{cc}
}

func (c *authServiceClient) Authenticate(ctx context.Context, in *AuthRequest, opts ...grpc.CallOption) (*AuthResponse, error) {
	out := new(AuthResponse)
	err := grpc.Invoke(ctx, "/models.AuthService/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *authServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*GetUserResponse, error) {
	out := new(GetUserResponse)
	err := grpc.Invoke(ctx, "/models.AuthService/GetUser", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for AuthService service

type AuthServiceServer interface {
	Authenticate(context.Context, *AuthRequest) (*AuthResponse, error)
	GetUser(context.Context, *GetUserRequest) (*GetUserResponse, error)
}

func RegisterAuthServiceServer(s *grpc.Server, srv AuthServiceServer) {
	s.RegisterService(&_AuthService_serviceDesc, srv)
}

func _AuthService_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.AuthService/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).Authenticate(ctx, req.(*AuthRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AuthService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AuthServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/models.AuthService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AuthServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _AuthService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "models.AuthService",
	HandlerType: (*AuthServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _AuthService_Authenticate_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _AuthService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 301 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xb1, 0x4e, 0xfb, 0x30,
	0x10, 0xc6, 0x95, 0xf4, 0xdf, 0xfe, 0x8b, 0x29, 0x05, 0x8e, 0x8a, 0x56, 0x11, 0x43, 0xe4, 0xa9,
	0x62, 0x48, 0x04, 0x6c, 0x2c, 0x88, 0xa9, 0x7b, 0x10, 0xec, 0xa6, 0x3e, 0xa5, 0x96, 0x12, 0x3b,
	0xe4, 0x9c, 0x32, 0x20, 0x16, 0x5e, 0x81, 0xa7, 0xe1, 0x39, 0x78, 0x05, 0x1e, 0x04, 0xd5, 0x4e,
	0x2a, 0x0a, 0xdb, 0xdd, 0xe5, 0xf2, 0xbb, 0xef, 0xfb, 0xcc, 0x0e, 0x08, 0xeb, 0xb5, 0x5a, 0x62,
	0x52, 0xd5, 0xc6, 0x1a, 0x18, 0x94, 0x46, 0x62, 0x41, 0xd1, 0x59, 0x6e, 0x4c, 0x5e, 0x60, 0x2a,
	0x2a, 0x95, 0x0a, 0xad, 0x8d, 0x15, 0x56, 0x19, 0x4d, 0x7e, 0x8b, 0xdf, 0xb0, 0xfd, 0xdb, 0xc6,
	0xae, 0x32, 0x7c, 0x6a, 0x90, 0x2c, 0x4c, 0x58, 0x1f, 0x4b, 0xa1, 0x8a, 0x59, 0x10, 0x07, 0xf3,
	0xbd, 0xcc, 0x37, 0x10, 0xb1, 0x61, 0x25, 0x88, 0x9e, 0x4d, 0x2d, 0x67, 0xa1, 0xfb, 0xb0, 0xed,
	0x39, 0x67, 0x23, 0x0f, 0xa0, 0xca, 0x68, 0x42, 0x00, 0xf6, 0x4f, 0x1a, 0x8d, 0x0e, 0x30, 0xcc,
	0x5c, 0xcd, 0x63, 0x36, 0x5e, 0xa0, 0xbd, 0x27, 0xac, 0xbb, 0x3b, 0x63, 0x16, 0x2a, 0xd9, 0x1e,
	0x09, 0x95, 0xe4, 0x0b, 0x76, 0xb8, 0xdd, 0x68, 0x41, 0xbf, 0x56, 0x36, 0x60, 0x2d, 0x4a, 0x6c,
	0x05, 0xb8, 0x1a, 0x8e, 0x58, 0x4f, 0xe4, 0x38, 0xeb, 0xc5, 0xc1, 0xbc, 0x9f, 0x6d, 0xca, 0xcb,
	0x8f, 0xc0, 0x1b, 0xba, 0xf3, 0x59, 0x40, 0xe6, 0xe5, 0xa1, 0xb6, 0x6a, 0x29, 0x2c, 0xc2, 0x49,
	0xe2, 0x63, 0x49, 0x7e, 0xb8, 0x8e, 0x26, 0xbb, 0x43, 0x2f, 0x80, 0x4f, 0xdf, 0x3e, 0xbf, 0xde,
	0xc3, 0x63, 0x3e, 0x72, 0xd1, 0xad, 0x2f, 0x52, 0xd1, 0xd8, 0xd5, 0x75, 0x70, 0x0e, 0x0f, 0xec,
	0x7f, 0x2b, 0x16, 0x4e, 0xbb, 0x3f, 0x77, 0xfd, 0x45, 0xd3, 0x3f, 0xf3, 0x16, 0x1a, 0x39, 0xe8,
	0x04, 0xa0, 0x83, 0x36, 0x84, 0x35, 0xa5, 0x2f, 0x4a, 0xbe, 0x3e, 0x0e, 0xdc, 0x93, 0x5c, 0x7d,
	0x07, 0x00, 0x00, 0xff, 0xff, 0x21, 0x5c, 0x97, 0x0c, 0xc9, 0x01, 0x00, 0x00,
}
