version: '2'
services:
  proxy:
    build: './proxy'
    volumes:
      - ./proxy/envoy.json:/etc/envoy.json
    networks:
      - envoymesh
    links:
      - service
      - hello
    ports:
      - 8080:10000
      - 9000:9000
    expose:
      - 8080
      - 9000

  service:
    build: './service'
    networks:
      envoymesh:
        aliases:
          - service
    ports:
      - 50051
    expose:
      - 50051

  hello:
    container_name: hello
    build: './hello-service'
    networks:
      envoymesh:
        aliases:
          - hello
    ports:
      - 50052
    expose:
      - 50052

networks:
  envoymesh: {}
