version: '2'
services:

  consul:
    image: consul
    depends_on:
      - service
      - hello
    ports:
      - 8500:8500

  proxy:
    build: './proxy'
    volumes:
      - ./proxy/envoy.json:/etc/envoy.json
      - ./proto.pb:/etc/defs.pb
    networks:
      - envoymesh
    depends_on:
      - service
      - hello
    links:
      - service
      - hello
    ports:
      - 8080:10000
      - 9000:9000
    expose:
      - 8080
      - 9000

  service:
    container_name: service
    build: './service'
    networks:
      envoymesh:
        aliases:
          - service
    ports:
      - 50051:50051
    expose:
      - 50051

  hello:
    container_name: hello
    build: './hello-service'
    networks:
      envoymesh:
        aliases:
          - hello
    ports:
      - 50052:50052
    expose:
      - 50052

networks:
  envoymesh: {}
